export interface ClassProfileData {
  hitDie: number
  savingThrows: string[]
  armorProficiencies: string[]
  weaponProficiencies: string[]
  toolProficiencies: string[]
  skillChoices: { count: number; from: string[] }
  spellcastingAbility: string | null
  startingHp: number  // hit die max value (same as hitDie)
  startingEquipment: string
  startingGold?: number  // 2024 PHB Option B: gold instead of class equipment
}

export const CLASS_PROFILE_DATA: Record<string, ClassProfileData> = {
  Artificer: {
    hitDie: 8,
    savingThrows: ['Constitution', 'Intelligence'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons'],
    toolProficiencies: ["Thieves' Tools", "Tinker's Tools", "One type of Artisan's Tools"],
    skillChoices: { count: 2, from: ['Arcana', 'History', 'Investigation', 'Medicine', 'Nature', 'Perception', 'Sleight of Hand'] },
    spellcastingAbility: 'intelligence',
    startingHp: 8,
    startingEquipment: "Studded Leather Armor, Dagger, Thieves' Tools, Tinker's Tools, Dungeoneer's Pack, 16 GP",
    startingGold: 75,
  },
  Barbarian: {
    hitDie: 12,
    savingThrows: ['Strength', 'Constitution'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons', 'Martial Weapons'],
    toolProficiencies: [],
    skillChoices: { count: 2, from: ['Animal Handling', 'Athletics', 'Intimidation', 'Nature', 'Perception', 'Survival'] },
    spellcastingAbility: null,
    startingHp: 12,
    startingEquipment: "Greataxe, Handaxe (2), Explorer's Pack, Javelin (4)",
    startingGold: 75,
  },
  Bard: {
    hitDie: 8,
    savingThrows: ['Dexterity', 'Charisma'],
    armorProficiencies: ['Light Armor'],
    weaponProficiencies: ['Simple Weapons', 'Hand Crossbows', 'Longswords', 'Rapiers', 'Shortswords'],
    toolProficiencies: ['Three Musical Instruments'],
    skillChoices: { count: 3, from: ['Acrobatics', 'Animal Handling', 'Arcana', 'Athletics', 'Deception', 'History', 'Insight', 'Intimidation', 'Investigation', 'Medicine', 'Nature', 'Perception', 'Performance', 'Persuasion', 'Religion', 'Sleight of Hand', 'Stealth', 'Survival'] },
    spellcastingAbility: 'charisma',
    startingHp: 8,
    startingEquipment: "Rapier, Diplomat's Pack, Lute, Leather Armor, Dagger",
    startingGold: 75,
  },
  Cleric: {
    hitDie: 8,
    savingThrows: ['Wisdom', 'Charisma'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons'],
    toolProficiencies: [],
    skillChoices: { count: 2, from: ['History', 'Insight', 'Medicine', 'Persuasion', 'Religion'] },
    spellcastingAbility: 'wisdom',
    startingHp: 8,
    startingEquipment: "Mace, Scale Mail, Light Crossbow, Bolts (20), Priest's Pack, Shield, Holy Symbol",
    startingGold: 75,
  },
  Barriomancer: {
    hitDie: 10,
    savingThrows: ['Charisma', 'Intelligence'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Heavy Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons'],
    toolProficiencies: [],
    skillChoices: { count: 3, from: ['Acrobatics', 'Arcana', 'Athletics', 'Insight', 'Investigation', 'Medicine', 'Perception', 'Sleight of Hand'] },
    spellcastingAbility: 'charisma',
    startingHp: 10,
    startingEquipment: "Simple Weapon and Shield or two Simple Weapons, Leather or Hide or Chain Mail, Dungeoneer's Pack or Explorer's Pack",
    startingGold: 125,
  },
  'Dragon-Rider': {
    hitDie: 10,
    savingThrows: ['Strength', 'Wisdom'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons', 'Martial Weapons'],
    toolProficiencies: ["Choose one from Cartographer's Tools, Herbalism Kit, or Navigator's Tools"],
    skillChoices: { count: 3, from: ['Animal Handling', 'Athletics', 'Insight', 'Nature', 'Perception', 'Stealth', 'Survival'] },
    spellcastingAbility: null,
    startingHp: 10,
    startingEquipment: "Scale Mail or Leather Armor, Martial Weapon and Shield or two Martial Weapons, Longbow with 20 arrows or 2 Handaxes, Explorer's Pack and Riding Harness",
    startingGold: 100,
  },
  Druid: {
    hitDie: 8,
    savingThrows: ['Intelligence', 'Wisdom'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Shields'],
    weaponProficiencies: ['Clubs', 'Daggers', 'Darts', 'Javelins', 'Maces', 'Quarterstaffs', 'Scimitars', 'Sickles', 'Slings', 'Spears'],
    toolProficiencies: ['Herbalism Kit'],
    skillChoices: { count: 2, from: ['Arcana', 'Animal Handling', 'Insight', 'Medicine', 'Nature', 'Perception', 'Religion', 'Survival'] },
    spellcastingAbility: 'wisdom',
    startingHp: 8,
    startingEquipment: "Wooden Shield, Scimitar, Leather Armor, Explorer's Pack, Druidic Focus",
    startingGold: 75,
  },
  Fighter: {
    hitDie: 10,
    savingThrows: ['Strength', 'Constitution'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Heavy Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons', 'Martial Weapons'],
    toolProficiencies: [],
    skillChoices: { count: 2, from: ['Acrobatics', 'Animal Handling', 'Athletics', 'History', 'Insight', 'Intimidation', 'Perception', 'Survival'] },
    spellcastingAbility: null,
    startingHp: 10,
    startingEquipment: "Chain Mail, Longsword, Shield, Light Crossbow, Bolts (20), Dungeoneer's Pack",
    startingGold: 150,
  },
  Monk: {
    hitDie: 8,
    savingThrows: ['Strength', 'Dexterity'],
    armorProficiencies: [],
    weaponProficiencies: ['Simple Weapons', 'Shortswords'],
    toolProficiencies: ["One Artisan's Tools or Musical Instrument"],
    skillChoices: { count: 2, from: ['Acrobatics', 'Athletics', 'History', 'Insight', 'Religion', 'Stealth'] },
    spellcastingAbility: null,
    startingHp: 8,
    startingEquipment: "Shortsword, Dungeoneer's Pack, Dart (10)",
    startingGold: 50,
  },
  Paladin: {
    hitDie: 10,
    savingThrows: ['Wisdom', 'Charisma'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Heavy Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons', 'Martial Weapons'],
    toolProficiencies: [],
    skillChoices: { count: 2, from: ['Athletics', 'Insight', 'Intimidation', 'Medicine', 'Persuasion', 'Religion'] },
    spellcastingAbility: 'charisma',
    startingHp: 10,
    startingEquipment: "Chain Mail, Longsword, Shield, Javelin (5), Priest's Pack, Holy Symbol",
    startingGold: 150,
  },
  Ranger: {
    hitDie: 10,
    savingThrows: ['Strength', 'Dexterity'],
    armorProficiencies: ['Light Armor', 'Medium Armor', 'Shields'],
    weaponProficiencies: ['Simple Weapons', 'Martial Weapons'],
    toolProficiencies: [],
    skillChoices: { count: 3, from: ['Animal Handling', 'Athletics', 'Insight', 'Investigation', 'Nature', 'Perception', 'Stealth', 'Survival'] },
    spellcastingAbility: 'wisdom',
    startingHp: 10,
    startingEquipment: "Scale Mail, Shortsword (2), Explorer's Pack, Longbow, Quiver, Arrows (20)",
    startingGold: 75,
  },
  Rogue: {
    hitDie: 8,
    savingThrows: ['Dexterity', 'Intelligence'],
    armorProficiencies: ['Light Armor'],
    weaponProficiencies: ['Simple Weapons', 'Hand Crossbows', 'Longswords', 'Rapiers', 'Shortswords'],
    toolProficiencies: ["Thieves' Tools"],
    skillChoices: { count: 4, from: ['Acrobatics', 'Athletics', 'Deception', 'Insight', 'Intimidation', 'Investigation', 'Perception', 'Performance', 'Persuasion', 'Sleight of Hand', 'Stealth'] },
    spellcastingAbility: null,
    startingHp: 8,
    startingEquipment: "Rapier, Shortbow, Quiver, Arrows (20), Burglar's Pack, Leather Armor, Dagger (2), Thieves' Tools",
    startingGold: 75,
  },
  Sorcerer: {
    hitDie: 6,
    savingThrows: ['Constitution', 'Charisma'],
    armorProficiencies: [],
    weaponProficiencies: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light Crossbows'],
    toolProficiencies: [],
    skillChoices: { count: 2, from: ['Arcana', 'Deception', 'Insight', 'Intimidation', 'Persuasion', 'Religion'] },
    spellcastingAbility: 'charisma',
    startingHp: 6,
    startingEquipment: "Light Crossbow, Bolts (20), Arcane Focus, Dungeoneer's Pack, Dagger (2)",
    startingGold: 50,
  },
  Warlock: {
    hitDie: 8,
    savingThrows: ['Wisdom', 'Charisma'],
    armorProficiencies: ['Light Armor'],
    weaponProficiencies: ['Simple Weapons'],
    toolProficiencies: [],
    skillChoices: { count: 2, from: ['Arcana', 'Deception', 'History', 'Intimidation', 'Investigation', 'Nature', 'Religion'] },
    spellcastingAbility: 'charisma',
    startingHp: 8,
    startingEquipment: "Light Crossbow, Bolts (20), Arcane Focus, Scholar's Pack, Leather Armor, Dagger (2)",
    startingGold: 75,
  },
  Wizard: {
    hitDie: 6,
    savingThrows: ['Intelligence', 'Wisdom'],
    armorProficiencies: [],
    weaponProficiencies: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light Crossbows'],
    toolProficiencies: [],
    skillChoices: { count: 2, from: ['Arcana', 'History', 'Insight', 'Investigation', 'Medicine', 'Religion'] },
    spellcastingAbility: 'intelligence',
    startingHp: 6,
    startingEquipment: "Quarterstaff, Arcane Focus, Scholar's Pack, Spellbook",
    startingGold: 50,
  },
}

export function getClassProfileData(className: string): ClassProfileData | undefined {
  return CLASS_PROFILE_DATA[className]
}
