/**
 * Local spell descriptions for spells not available in the Open5e/SRD API.
 * These cover spells from XGE, TCE, FTD, Strixhaven, SCAG, and other non-SRD sources.
 * Used as a fallback when the API can't find a spell.
 */

export interface LocalSpellData {
  name: string
  level: number
  school: string
  castingTime: string
  range: string
  components: string
  duration: string
  concentration: boolean
  ritual: boolean
  description: string
  higherLevels?: string
}

const SPELLS: Record<string, LocalSpellData> = {
  // ─── CANTRIPS ───
  'booming-blade': { name: 'Booming Blade', level: 0, school: 'Evocation', castingTime: '1 action', range: 'Self (5-foot radius)', components: 'S, M (a melee weapon worth at least 1 sp)', duration: '1 round', concentration: false, ritual: false, description: 'You brandish the weapon used in the spell\'s casting and make a melee attack with it against one creature within 5 feet of you. On a hit, the target suffers the weapon attack\'s normal effects and then becomes sheathed in booming energy until the start of your next turn. If the target willingly moves 5 feet or more before then, the target takes 1d8 thunder damage, and the spell ends.', higherLevels: 'At 5th level, the melee attack deals an extra 1d8 thunder damage to the target on a hit, and the damage the target takes for moving increases to 2d8. Both damage rolls increase by 1d8 at 11th level (2d8 and 3d8) and again at 17th level (3d8 and 4d8).' },
  'create-bonfire': { name: 'Create Bonfire', level: 0, school: 'Conjuration', castingTime: '1 action', range: '60 feet', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'You create a bonfire on ground that you can see within range. Until the spell ends, the bonfire fills a 5-foot cube. Any creature in the bonfire\'s space when you cast the spell must succeed on a Dexterity saving throw or take 1d8 fire damage. A creature must also make the saving throw when it moves into the bonfire\'s space for the first time on a turn or ends its turn there.', higherLevels: 'The spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).' },
  'frostbite': { name: 'Frostbite', level: 0, school: 'Evocation', castingTime: '1 action', range: '60 feet', components: 'V, S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You cause numbing frost to form on one creature that you can see within range. The target must make a Constitution saving throw. On a failed save, the target takes 1d6 cold damage, and it has disadvantage on the next weapon attack roll it makes before the end of its next turn.', higherLevels: 'The spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).' },
  'green-flame-blade': { name: 'Green-Flame Blade', level: 0, school: 'Evocation', castingTime: '1 action', range: 'Self (5-foot radius)', components: 'S, M (a melee weapon worth at least 1 sp)', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You brandish the weapon used in the spell\'s casting and make a melee attack with it against one creature within 5 feet of you. On a hit, the target suffers the weapon attack\'s normal effects, and you can cause green fire to leap from the target to a different creature of your choice that you can see within 5 feet of it. The second creature takes fire damage equal to your spellcasting ability modifier.', higherLevels: 'At 5th level, the melee attack deals an extra 1d8 fire damage to the target on a hit, and the fire damage to the second creature increases to 1d8 + your spellcasting ability modifier. Both damage rolls increase by 1d8 at 11th level and 17th level.' },
  'gust': { name: 'Gust', level: 0, school: 'Transmutation', castingTime: '1 action', range: '30 feet', components: 'V, S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You seize the air and compel it to create one of the following effects at a point you can see within range: One Medium or smaller creature must succeed on a Strength saving throw or be pushed up to 5 feet away from you. You create a small blast of air capable of moving one object that is neither held nor carried and that weighs no more than 5 pounds. You create a harmless sensory effect using air.' },
  'infestation': { name: 'Infestation', level: 0, school: 'Conjuration', castingTime: '1 action', range: '30 feet', components: 'V, S, M (a living flea)', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You cause a cloud of mites, fleas, and other parasites to appear momentarily on one creature you can see within range. The target must succeed on a Constitution saving throw, or it takes 1d6 poison damage and moves 5 feet in a random direction.', higherLevels: 'The spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).' },
  'lightning-lure': { name: 'Lightning Lure', level: 0, school: 'Evocation', castingTime: '1 action', range: 'Self (15-foot radius)', components: 'V', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You create a lash of lightning energy that strikes at one creature of your choice that you can see within 15 feet of you. The target must succeed on a Strength saving throw or be pulled up to 10 feet in a straight line toward you and then take 1d8 lightning damage if it is within 5 feet of you.', higherLevels: 'The spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).' },
  'mind-sliver': { name: 'Mind Sliver', level: 0, school: 'Enchantment', castingTime: '1 action', range: '60 feet', components: 'V', duration: '1 round', concentration: false, ritual: false, description: 'You drive a disorienting spike of psychic energy into the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.', higherLevels: 'The spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).' },
  'primal-savagery': { name: 'Primal Savagery', level: 0, school: 'Transmutation', castingTime: '1 action', range: 'Self', components: 'S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You channel primal magic to cause your teeth or fingernails to sharpen, ready to deliver a corrosive attack. Make a melee spell attack against one creature within 5 feet of you. On a hit, the target takes 1d10 acid damage. After you make the attack, your teeth or fingernails return to normal.', higherLevels: 'The spell\'s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).' },
  'sword-burst': { name: 'Sword Burst', level: 0, school: 'Conjuration', castingTime: '1 action', range: 'Self (5-foot radius)', components: 'V', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You create a momentary circle of spectral blades that sweep around you. All other creatures within 5 feet of you must succeed on a Dexterity saving throw or take 1d6 force damage.', higherLevels: 'The spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).' },
  'thunderclap': { name: 'Thunderclap', level: 0, school: 'Evocation', castingTime: '1 action', range: 'Self (5-foot radius)', components: 'S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You create a burst of thunderous sound that can be heard up to 100 feet away. Each creature within range, other than you, must succeed on a Constitution saving throw or take 1d6 thunder damage.', higherLevels: 'The spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).' },
  'toll-the-dead': { name: 'Toll the Dead', level: 0, school: 'Necromancy', castingTime: '1 action', range: '60 feet', components: 'V, S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage.', higherLevels: 'The spell\'s damage increases by one die when you reach 5th level (2d8 or 2d12), 11th level (3d8 or 3d12), and 17th level (4d8 or 4d12).' },
  'word-of-radiance': { name: 'Word of Radiance', level: 0, school: 'Evocation', castingTime: '1 action', range: '5 feet', components: 'V, M (a holy symbol)', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You utter a divine word, and burning radiance erupts from you. Each creature of your choice that you can see within range must succeed on a Constitution saving throw or take 1d6 radiant damage.', higherLevels: 'The spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).' },

  // ─── 1ST LEVEL ───
  'absorb-elements': { name: 'Absorb Elements', level: 1, school: 'Abjuration', castingTime: '1 reaction, which you take when you take acid, cold, fire, lightning, or thunder damage', range: 'Self', components: 'S', duration: '1 round', concentration: false, ritual: false, description: 'The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends.', higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the extra damage increases by 1d6 for each slot level above 1st.' },
  'catapult': { name: 'Catapult', level: 1, school: 'Transmutation', castingTime: '1 action', range: '60 feet', components: 'S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'Choose one object weighing 1 to 5 pounds within range that isn\'t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving. The target takes 3d8 bludgeoning damage.', higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects increases by 5 pounds, and the damage increases by 1d8, for each slot level above 1st.' },
  'cause-fear': { name: 'Cause Fear', level: 1, school: 'Necromancy', castingTime: '1 action', range: '60 feet', components: 'V', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'You awaken the sense of mortality in one creature you can see within range. A construct or an undead is immune to this effect. The target must succeed on a Wisdom saving throw or become frightened of you until the spell ends. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.' },
  'ceremony': { name: 'Ceremony', level: 1, school: 'Abjuration', castingTime: '1 hour', range: 'Touch', components: 'V, S, M (25 gp worth of powdered silver, which the spell consumes)', duration: 'Instantaneous', concentration: false, ritual: true, description: 'You perform a special religious ceremony that is infused with magic. When you cast the spell, choose one of the rites described (Atonement, Bless Water, Coming of Age, Dedication, Funeral Rite, Wedding). The target of the rite gains a benefit based on the ceremony chosen.' },
  'chaos-bolt': { name: 'Chaos Bolt', level: 1, school: 'Evocation', castingTime: '1 action', range: '120 feet', components: 'V, S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You hurl an undulating, warbling mass of chaotic energy at one creature in range. Make a ranged spell attack against the target. On a hit, the target takes 2d8 + 1d6 damage. Choose one of the d8s. The number rolled on that die determines the attack\'s damage type (1: Acid, 2: Cold, 3: Fire, 4: Force, 5: Lightning, 6: Poison, 7: Psychic, 8: Thunder). If you roll the same number on both d8s, the chaotic energy leaps to a different target within 30 feet and you make a new attack roll.', higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, each target takes 1d6 extra damage for each slot level above 1st.' },
  'earth-tremor': { name: 'Earth Tremor', level: 1, school: 'Evocation', castingTime: '1 action', range: '10 feet', components: 'V, S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You cause a tremor in the ground within 10 feet of you. Each creature other than you in that area must make a Dexterity saving throw. On a failed save, a creature takes 1d6 bludgeoning damage and is knocked prone. If the ground in that area is loose earth or stone, it becomes difficult terrain until cleared.' },
  'ice-knife': { name: 'Ice Knife', level: 1, school: 'Conjuration', castingTime: '1 action', range: '60 feet', components: 'S, M (a drop of water or piece of ice)', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You create a shard of ice and fling it at one creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 piercing damage. Hit or miss, the shard then explodes. The target and each creature within 5 feet of it must succeed on a Dexterity saving throw or take 2d6 cold damage.', higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the cold damage increases by 1d6 for each slot level above 1st.' },
  'silvery-barbs': { name: 'Silvery Barbs', level: 1, school: 'Enchantment', castingTime: '1 reaction, which you take when a creature you can see within 60 feet succeeds on an attack roll, ability check, or saving throw', range: '60 feet', components: 'V', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You magically distract the triggering creature and turn its momentary uncertainty into encouragement for another creature. The triggering creature must reroll the d20 and use the lower roll. You can then choose a different creature you can see within range (you can choose yourself). The chosen creature has advantage on the next attack roll, ability check, or saving throw it makes within 1 minute.' },
  'tashas-caustic-brew': { name: "Tasha's Caustic Brew", level: 1, school: 'Evocation', castingTime: '1 action', range: 'Self (30-foot line)', components: 'V, S, M (a bit of rotten food)', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'A stream of acid emanates from you in a line 30 feet long and 5 feet wide in a direction you choose. Each creature in the line must succeed on a Dexterity saving throw or be covered in acid for the spell\'s duration or until a creature uses its action to scrape or wash the acid off itself or another creature. A creature covered in the acid takes 2d4 acid damage at the start of each of its turns.', higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 2d4 for each slot level above 1st.' },
  'zephyr-strike': { name: 'Zephyr Strike', level: 1, school: 'Transmutation', castingTime: '1 bonus action', range: 'Self', components: 'V', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'You move like the wind. Until the spell ends, your movement doesn\'t provoke opportunity attacks. Once before the spell ends, you can give yourself advantage on one weapon attack roll on your turn. That attack deals an extra 1d8 force damage on a hit. Whether you hit or miss, your walking speed increases by 30 feet until the end of that turn.' },

  // ─── 2ND LEVEL ───
  'shadow-blade': { name: 'Shadow Blade', level: 2, school: 'Illusion', castingTime: '1 bonus action', range: 'Self', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'You weave together threads of shadow to create a sword of solidified gloom in your hand. This magic sword lasts until the spell ends. It counts as a simple melee weapon with which you are proficient. It deals 2d8 psychic damage on a hit and has the finesse, light, and thrown properties (range 20/60). If you drop the weapon or throw it, it dissipates at the end of the turn. You have advantage on attack rolls with this weapon if the target is in dim light or darkness.', higherLevels: 'When you cast this spell using a 3rd- or 4th-level spell slot, the damage increases to 3d8. When you cast it using a 5th- or 6th-level spell slot, the damage increases to 4d8. When you cast it using a spell slot of 7th level or higher, the damage increases to 5d8.' },
  'mind-spike': { name: 'Mind Spike', level: 2, school: 'Divination', castingTime: '1 action', range: '60 feet', components: 'S', duration: 'Concentration, up to 1 hour', concentration: true, ritual: false, description: 'You reach into the mind of one creature you can see within range. The target must make a Wisdom saving throw, taking 3d8 psychic damage on a failed save, or half as much on a successful one. On a failed save, you also always know the target\'s location until the spell ends, but only while the two of you are on the same plane. While you have this knowledge, the target can\'t become hidden from you, and if it\'s invisible, it gains no benefit from that condition against you.', higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.' },
  'tashas-mind-whip': { name: "Tasha's Mind Whip", level: 2, school: 'Enchantment', castingTime: '1 action', range: '90 feet', components: 'V', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You psychically lash out at one creature you can see within range. The target must make an Intelligence saving throw. On a failed save, the target takes 3d6 psychic damage, and it can\'t take a reaction until the end of its next turn. Moreover, on its next turn, it must choose whether it gets a move, an action, or a bonus action; it gets only one of the three. On a successful save, the target takes half as much damage and suffers none of the spell\'s other effects.', higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.' },
  'kinetic-jaunt': { name: 'Kinetic Jaunt', level: 2, school: 'Transmutation', castingTime: '1 bonus action', range: 'Self', components: 'S', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'You magically empower your movement. For the duration, your walking speed increases by 10 feet, and your movement doesn\'t provoke opportunity attacks. You can also move through the space of another creature. If you end your turn in a creature\'s space, you are shunted to the last unoccupied space you occupied.' },
  'vortex-warp': { name: 'Vortex Warp', level: 2, school: 'Conjuration', castingTime: '1 action', range: '90 feet', components: 'V, S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You magically twist space around another creature you can see within range. The target must succeed on a Constitution saving throw (the target can choose to fail), or the target is teleported to an unoccupied space of your choice that you can see within range. The chosen space must be on a surface or in a liquid that can support the target without the target having to squeeze.', higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the range of the spell increases by 30 feet for each slot level above 2nd.' },

  // ─── 3RD LEVEL ───
  'spirit-shroud': { name: 'Spirit Shroud', level: 3, school: 'Necromancy', castingTime: '1 bonus action', range: 'Self', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'You call forth spirits of the dead, which flit around you for the spell\'s duration. The spirits are intangible and invulnerable. Until the spell ends, any attack you make deals 1d8 extra damage when you hit a creature within 10 feet of you. This damage is radiant, necrotic, or cold (your choice when you cast the spell). Any creature that takes this damage can\'t regain hit points until the start of your next turn. In addition, any creature of your choice within 10 feet of you has its speed reduced by 10 feet.', higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d8 for every two slot levels above 3rd.' },
  'intellect-fortress': { name: 'Intellect Fortress', level: 3, school: 'Abjuration', castingTime: '1 action', range: '30 feet', components: 'V', duration: 'Concentration, up to 1 hour', concentration: true, ritual: false, description: 'For the duration, you or one willing creature you can see within range has resistance to psychic damage, as well as advantage on Intelligence, Wisdom, and Charisma saving throws.', higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.' },
  'thunder-step': { name: 'Thunder Step', level: 3, school: 'Conjuration', castingTime: '1 action', range: '90 feet', components: 'V', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You teleport yourself to an unoccupied space you can see within range. Immediately after you disappear, a thunderous boom sounds, and each creature within 10 feet of the space you left must make a Constitution saving throw, taking 3d10 thunder damage on a failed save, or half as much on a successful one. You can also teleport one willing creature you\'re touching to an unoccupied space within 5 feet of your destination.', higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d10 for each slot level above 3rd.' },
  'summon-fey': { name: 'Summon Fey', level: 3, school: 'Conjuration', castingTime: '1 action', range: '90 feet', components: 'V, S, M (a gilded flower worth at least 300 gp)', duration: 'Concentration, up to 1 hour', concentration: true, ritual: false, description: 'You call forth a fey spirit. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Fey Spirit stat block. When you cast the spell, choose a mood: Fuming, Mirthful, or Tricksy. The creature\'s attacks deal extra damage and gain additional effects based on the chosen mood. The spirit is friendly to you and your companions. In combat, it shares your initiative count but takes its turn immediately after yours.' },
  'enemies-abound': { name: 'Enemies Abound', level: 3, school: 'Enchantment', castingTime: '1 action', range: '120 feet', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'You reach into the mind of one creature you can see and force it to make an Intelligence saving throw. On a failed save, the target loses the ability to distinguish friend from foe, regarding all creatures it can see as enemies until the spell ends. Each time the target takes damage, it can repeat the saving throw, ending the effect on itself on a success. When the affected creature chooses targets, it must choose the target at random from among the creatures it can see within range of the attack, spell, or other ability it\'s using.' },

  // ─── 4TH LEVEL ───
  'sickening-radiance': { name: 'Sickening Radiance', level: 4, school: 'Evocation', castingTime: '1 action', range: '120 feet', components: 'V, S', duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false, description: 'Dim, greenish light spreads within a 30-foot-radius sphere centered on a point you choose within range. The light spreads around corners, and it lasts until the spell ends. When a creature moves into the spell\'s area for the first time on a turn or starts its turn there, that creature must succeed on a Constitution saving throw or take 4d10 radiant damage, and it suffers one level of exhaustion and emits a dim, greenish light in a 5-foot radius. This light makes it impossible for the creature to benefit from being invisible.' },
  'storm-sphere': { name: 'Storm Sphere', level: 4, school: 'Evocation', castingTime: '1 action', range: '150 feet', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true, ritual: false, description: 'A 20-foot-radius sphere of whirling air springs into existence centered on a point you choose within range. Each creature in the sphere when it appears or that ends its turn there must succeed on a Strength saving throw or take 2d6 bludgeoning damage. As a bonus action on each of your turns, you can cause a bolt of lightning to leap from the center of the sphere toward one creature you can see within 60 feet of the center, making a ranged spell attack. On a hit, the target takes 4d6 lightning damage.' },
  'raulothims-psychic-lance': { name: "Raulothim's Psychic Lance", level: 4, school: 'Enchantment', castingTime: '1 action', range: '120 feet', components: 'V', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You unleash a shimmering lance of psychic power from your forehead at a creature that you can see within range. Alternatively, you can utter a creature\'s name. If the named target is within range, it becomes the spell\'s target even if you can\'t see it. If the named target isn\'t within range, the lance dissipates without effect. The target must make an Intelligence saving throw. On a failed save, the target takes 7d6 psychic damage and is incapacitated until the start of your next turn. On a successful save, the creature takes half as much damage and isn\'t incapacitated.', higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d6 for each slot level above 4th.' },

  // ─── 5TH LEVEL ───
  'synaptic-static': { name: 'Synaptic Static', level: 5, school: 'Enchantment', castingTime: '1 action', range: '120 feet', components: 'V, S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You choose a point within range and cause psychic energy to explode there. Each creature in a 20-foot-radius sphere centered on that point must make an Intelligence saving throw. A creature with an Intelligence score of 2 or less isn\'t affected. On a failed save, a target takes 8d6 psychic damage and suffers muddled thoughts for 1 minute. A muddled target must roll a d6 and subtract the number rolled from all its attack rolls and ability checks, as well as its Constitution saving throws to maintain concentration. The target can make an Intelligence saving throw at the end of each of its turns, ending the effect on itself on a success.' },
  'steel-wind-strike': { name: 'Steel Wind Strike', level: 5, school: 'Conjuration', castingTime: '1 action', range: '30 feet', components: 'S, M (a melee weapon worth at least 1 sp)', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You flourish the weapon used in the casting and then vanish to strike like the wind. Choose up to five creatures you can see within range. Make a melee spell attack against each target. On a hit, a target takes 6d10 force damage. You can then teleport to an unoccupied space you can see within 5 feet of one of the targets you hit or missed.' },
  'holy-weapon': { name: 'Holy Weapon', level: 5, school: 'Evocation', castingTime: '1 bonus action', range: 'Touch', components: 'V, S', duration: 'Concentration, up to 1 hour', concentration: true, ritual: false, description: 'You imbue a weapon you touch with holy power. Until the spell ends, the weapon emits bright light in a 30-foot radius and dim light for an additional 30 feet. In addition, weapon attacks made with it deal an extra 2d8 radiant damage on a hit. If the weapon isn\'t already a magic weapon, it becomes one for the duration. As a bonus action, you can dismiss this spell and cause the weapon to emit a burst of radiance. Each creature of your choice within 30 feet must make a Constitution saving throw, taking 4d8 radiant damage on a failed save, or half as much on a successful one.' },

  // ─── 9TH LEVEL ───
  'psychic-scream': { name: 'Psychic Scream', level: 9, school: 'Enchantment', castingTime: '1 action', range: '90 feet', components: 'S', duration: 'Instantaneous', concentration: false, ritual: false, description: 'You unleash the power of your mind to blast the intellect of up to ten creatures of your choice that you can see within range. Creatures that have an Intelligence score of 2 or lower are unaffected. Each target must make an Intelligence saving throw. On a failed save, a target takes 14d6 psychic damage and is stunned. On a successful save, a target takes half as much damage and isn\'t stunned. If a target is killed by this damage, its head explodes, assuming it has one. A stunned target can make an Intelligence saving throw at the end of each of its turns. On a successful save, the stunning effect ends.' },
}

/** Look up a local spell description by index (slug). Returns null if not found. */
export function getLocalSpellData(index: string): LocalSpellData | null {
  return SPELLS[index] ?? null
}
